### ISSUE TITLE
connections.db missing when tool installed locally.

### ISSUE THREAD

**Issue by mwwhited** [faesel/az-lazy#102]
When az-lazy is only installed as a local .net tool it reports and error missing a "connections.db"

`Unhandled exception. System.IO.DirectoryNotFoundException: Could not find a part of the path '%USERPROFILE%\.dotnet\tools\.store\az-lazy\connections.db'.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at LiteDB.Engine.FileStreamFactory.GetStream(Boolean canWrite, Boolean sequencial)
   at LiteDB.Engine.StreamPool.<>c__DisplayClass3_0.<.ctor>b__0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at LiteDB.Engine.StreamPool.get_Writer()
   at LiteDB.Engine.DiskService..ctor(EngineSettings settings, Int32[] memorySegmentSizes)
   at LiteDB.Engine.LiteEngine..ctor(EngineSettings settings)
   at LiteDB.ConnectionString.CreateEngine()
   at LiteDB.LiteDatabase..ctor(ConnectionString connectionString, BsonMapper mapper)
   at LiteDB.LiteDatabase..ctor(String connectionString, BsonMapper mapper)
   at az_lazy.Manager.LocalStorageManager.AddDevelopmentConnection() in C:\code\faesel\az-lazy\az-lazy\Manager\LocalStorageManager.cs:line 57
   at az_lazy.Program.Main(String[] args) in C:\code\faesel\az-lazy\az-lazy\Program.cs:line 19
   at az_lazy.Program.<Main>(String[] args)
`

**Comment by faesel** [comment]
Thanks for reporting this, initially it was designed as a global tool. Will look into adding support as a local tool.

**Comment by mwwhited** [comment]
> Thanks for reporting this, initially it was designed as a global tool. Will look into adding support as a local tool. 

No worries, it works great.  I was just trying to use it as a local tool so my devs could just "dotnet tool restore" and get everything. If you update it fantastic, if not it still works great.
